CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL
);

CREATE TABLE projects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(50) NOT NULL,
                          description VARCHAR(500),
                          created_at TIMESTAMP NOT NULL,

                          owner_id BIGINT NOT NULL,

                          CONSTRAINT fk_project_owner
                              FOREIGN KEY (owner_id)
                                  REFERENCES users(id)
);

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(100) NOT NULL,
                       description VARCHAR(500),

                       status VARCHAR(30) NOT NULL,
                       priority VARCHAR(30) NOT NULL,

                       due_date DATE,
                       created_at TIMESTAMP NOT NULL,

                       project_id BIGINT NOT NULL,
                       assignee_id BIGINT NOT NULL,

                       CONSTRAINT fk_task_project
                           FOREIGN KEY (project_id)
                               REFERENCES projects(id),

                       CONSTRAINT fk_task_assignee
                           FOREIGN KEY (assignee_id)
                               REFERENCES users(id)
);