CREATE TABLE task_activities (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 action VARCHAR(100) NOT NULL,
                                 description VARCHAR(500),
                                 created_at TIMESTAMP NOT NULL,
                                 task_id BIGINT NOT NULL,

                                 CONSTRAINT fk_activity_task
                                     FOREIGN KEY (task_id)
                                         REFERENCES tasks(id)
);